version: "3"

services:
  postgres:
    container_name: postgres_container
    image: postgres:14
    restart: always
    volumes:
      - ./pgdata:/data/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docekr
      - POSTGRES_DB=bancodedados

  app:
    container_name: app-nodejs
    build: 
      context: .
      dockerfile: dockerfile-dev
    image: test-api
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT=3003
    ports:
      - "3003:3003"
    links:
      - postgres
    

