version: '3'

services:
  app:
    container_name: app-nodejs
    build: 
      context: .
      dockerfile: dockerfile-dev
    volumes:
      - ./:/usr/src/app
    environment:
      - PORT=3003
    ports:
      - 3003:3003